apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-graylog
  labels:
    k8s-app: {{ .Release.Name }}-graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}-graylog
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}-graylog
    spec:
      containers:
      - name: graylog5
        image: graylog/graylog:5.0
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: <password_salt_min_64_chars>
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: <password_in_sha2>
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://localhost:9000/
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://es.monitoring.svc.cluster.local:9200
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongo.monitoring.svc.cluster.local:27017/graylog
        ports:
        - containerPort: 9000
        - containerPort: 12201