apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graylog
spec:
  type: LoadBalancer
  selector:
    k8s-app: {{ .Release.Name }}-graylog
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    nodePort: 30003
  - name: "12201"
    port: 12201
    targetPort: 12201
    nodePort: 30004