apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-elasticsearch-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 100Gi
