apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    service: {{ .Release.Name }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:3
        ports:
        - containerPort: 27017


